### ISSUE TITLE
Data Visualization Community Survey 2019

### ISSUE THREAD

**Issue by venkatrajam** [info-design-lab/DE705-Interactive-Data-Visualization#2]
The data and design brief for the next assignment is [here](https://www.datavisualizationsociety.com/2019-survey-challenge).

**Comment by rishivanukuru** [comment]
# DVS Challenge, but Shiny

## Title: What We Viz With

> Update 27/10/2019: I re-wrote this comment for the final submission. Before this, it was just a collection of images/links, with not much information anyway.

### Beginning

From the dataset given to us by the Data Viz Society, the questions about tool usage were what caught my eye first. DVS members were asked about the specific tools they used, and what they used them for. In the question about specific tools, about 40 options were provided, along with a text field for other tools not mentioned in the 40. 

Before cleaning the data, I thought of creating simple visualisations using each of the top 10/15 tools, as a sort of meta-visualisation. This would have been a nice way to learn about a bunch of tools. After a discussion in class, an additional idea could have been to talk about my experience learning each of the tools as part of the overall piece of work. The first step in any case would be to find out how many tools were mentioned, and which were the most used among them.

Across all members, there ended up being **_140 other tools_** (181 in all) that were important enough to mention. Visualising the breadth of tools quickly became more interesting than learning a handful of them, and that is what I went with for the rest of the assignment.

### Negotiating with Data

Simple data cleaning ended up not being so. To reach a table that showed how many participants used each tool, I had to manually go through all distinct tool name entries, and combine those that were the same but written differently (MS Excel, Excel, xcel, Microsoft Excel, and so on). [OpenRefine](http://openrefine.org/) would have helped for single column replacements, but that was not the case here. 

Then, an unnecessary amount of pain, Google Sheets formulae, and js code snippets eventually led to a nice matrix that described which tools were used with which other tools.  

Both these tables were then unwittingly fed into the [Circos Online Circos Maker](http://mkweb.bcgsc.ca/tableviewer/), leading to these two hairballs:

**Tools to Participants, and Tools to Tools:**

![circos-table-intgeup-large](https://user-images.githubusercontent.com/12021065/65313452-00777080-dbb2-11e9-8dd2-59fedc492070.png)

![circos-table-oeiytkl-large](https://user-images.githubusercontent.com/12021065/65313491-0e2cf600-dbb2-11e9-9fed-89dfbdd1cc55.png)

There obviously were far too many data points to use Circos as an effective means of visualising the relationship between tools. At this point, I thought of depicting these relationships as a network, where the size of a tool's node represented the number of people using that tool. The thickness of the link between tools could be indicative of the number of people using both tools.

I used crayons to draw what I hoped to execute:

![IMG_20190920_142053636](https://user-images.githubusercontent.com/12021065/65313708-72e85080-dbb2-11e9-842e-81acc33bd1f8.jpg)

### Networking

I spent some time exploring a bunch of options for network creation. [Gephi](https://gephi.org/) would have been nice. The issue was that it required the data to be in a particular Markup format, and I didn't want to go through the process of translating the tables I had. There were a few js based options, most prominently [Sigma.js](http://sigmajs.org/), but there were issues with data porting and interactivity that I wasn't able to quickly resolve.

[R Shiny](https://shiny.rstudio.com/) was the tool I presented in class. You can read more about it in my post [here](https://github.com/info-design-lab/DE705-Autumn-2019/issues/3#issuecomment-546625779). Given the size of the matrix I was dealing with, and the lack of any clear option otherwise, I thought it made sense to try and execute this project in R Shiny itself. 

R has an immense range of packages for all kinds of specialised functions. I found one fairly accessible library for simple networks, and fed the data I had into that. This is what managed to create:

![Rplot](https://user-images.githubusercontent.com/12021065/65313434-f81f3580-dbb1-11e9-9732-94f6169ddc0a.png)

This was nowhere close to what I had drawn on paper.

Luckily, I found that R has a really useful package for [Force-Directed graphs](https://en.wikipedia.org/wiki/Force-directed_graph_drawing), that had already been optimised for Shiny deployment. The package is called [networkd3](https://christophergandrud.github.io/networkD3/), and is a port of a d3 package for force-directed graphs.

### Networks, but Shiny

#### _A hint of what is to come_
![DVS_Diamond](https://user-images.githubusercontent.com/12021065/67638672-39230c00-f90d-11e9-8500-968c84d2d4a2.png)

To make a basic network work using this package, you need two tables:

-  A Node table, with information about each tool, the unique ID number of the tool, and size of the node (number of people using the tool in this case)
- A Link table, with information about all the links between nodes, and the strength of each link (which in this case is the number of people using both tools)

The Node table was already in place from earlier work. The Link table was created by summing each row/column of the tool matrix mentioned a few paragraphs ago. 

There are quite a few parameters that can be modified to customize the appearance of a graph through this package. The documentation available at [CRAN](https://cran.r-project.org/web/packages/networkD3/networkD3.pdf), and on [this page](https://christophergandrud.github.io/networkD3/), proved to be fairly comprehensive and very useful. I had to play around with all possible variables - link size, node size, node repulsion, colours, text sizes, and opacity to name some - till a good enough network was reached. 

After this came the fun part. I had to manually go through all tools, and try and categorise them into some kind of grouping. This was needed in order to be able to colour-code the nodes in some manner. I had never heard of most of the tools before, so this required me to read up about them and figure out which group they fit into best. I ended up with about 12 groups. Some categories were - Spreadsheets, Javascript-based, Python-based, Business Intelligence, Network Generators and In-House tools. I then used a categorical colour scale to differentiate between nodes belonging to the various groups.

At this point I realised that it was possible to add on-click events to each of the nodes. This meant that I could theoretically allow users to click on nodes and get more information about each tool. I decided to go ahead and implement this. The method of attaching a js snippet to the node is simple and well-documented. I searched for relevant links for all tools, made a new table containing that information, and used that to display information on the page.

The layout of the Shiny page was taken care of by [Bootstrap](https://getbootstrap.com/) (which is integrated into Shiny). I changed the theme to a dark one, and played around with the positioning of the information panel. Everything was working fine from inside R, but upon deploying the final code online, the page wasn't responding to the window size. I spent an evening trying to fix that, but was ultimately unable to figure out what was going wrong. The final visualisation works best when you zoom out in browser, and doesn't work at all on mobile. I'll get back to this at some point in the future and see if I can fix it.

### Sending in the entry

Finally, the title, "What We Viz With", was chosen primarily because it was alliterative. The link I submitted to the challenge can be found [here](https://rishivanukuru.shinyapps.io/DVS-Challenge/) (Zoom out to about 90% for best results).

Here's an image of how it looks:

![annotwo](https://user-images.githubusercontent.com/12021065/67638713-d2522280-f90d-11e9-8687-cf85b8f979f4.jpg)

And all code involved in the final result can be found [here](https://github.com/vanukuru/DVS-Challenge).

In case you have any questions about anything mentioned here, feel free to ask.

That's all for now,
Rishi

------

**Comment by maulicule** [comment]
### Making sense of the data
Started out by trying to understand the survey itself. Simple encoding through symbols:

- circle: radio button (single select)
- square: check boxes (multiple select)

- scale: Likert rating

- ellipsis: allows for text entry(open-ended)


![image](https://user-images.githubusercontent.com/19164674/65253595-85ae4700-db18-11e9-8b9d-a66f229379e6.png)

### Cleaning the data
So far, the major component of the time invested in the exercise has been to clean to data and gain meaningful insights from it. It took several passes through the survey to look at potential (reliable) datapoints which could be utilized. Several fields allowed the interviewees to add their own options, some others were completely open-ended. My approach here was to use the initial understanding of the survey and to classify the data accordingly to nominal, ordinal, interval and ratio, which could then be used to base decisions like the representation to be used, the visual encoding to be employed, etc.

### Towards a PoC
Using Flourish to prototype to gauge diversity in terms of gender identity, years of dataviz experience, nationality, identification with LGBTQ+ community, etc.
Currently exploring an animated bubble chart representation. Given time and ability to code, I would like to use D3 and animate this (extremely optimistically!) similar to [Obama's Budget Sliced Four Ways by NYTimes]
(https://archive.nytimes.com/www.nytimes.com/interactive/2012/02/13/us/politics/2013-budget-proposal-graphic.html?hp)

Populating the graph with the initial dataset 
![01](https://user-images.githubusercontent.com/19164674/65324672-86071a80-dbca-11e9-85ad-ccee50d805c0.PNG)

Sized by years of Data Visualisation experience:
![02](https://user-images.githubusercontent.com/19164674/65324698-9d460800-dbca-11e9-8586-8a6dbd110271.PNG)

Shaded by Gender Identity
![03](https://user-images.githubusercontent.com/19164674/65324715-a59e4300-dbca-11e9-9004-0a910f9aef69.PNG)


![04](https://user-images.githubusercontent.com/19164674/65324728-b058d800-dbca-11e9-85d6-390ffdb02104.PNG)



> I am still working on coding it myself and streamlining the flow further, but it is a slow and time-consuming task, which I'm hoping to accomplish by and by

**The final version as of now**, is [here](https://public.flourish.studio/story/93750/), a Flourish Data Story with an animated bubble chart.

**Comment by mayura7** [comment]
After looking at the Survey, I thought of taking up the branch of thought leaders. I cleaned the data on excel (manually first and then sought help of open refine).  [Here](https://docs.google.com/spreadsheets/d/1YeIYzfKMVvu9kVAJm5rqbZceCjh691Qv8K197M5xQYI/edit?usp=sharing) is the cleaned data set. who

The data was mapped in terms of the names of thought leaders mentioned by the participants. I counted the number of times a name was mentioned in that year which became the popularity index. 
The counts were converted to percentage values in order to normalize the varying number of participants every year. This value was multiplied by 1000 and rounded off to 0 decimals so that the final number was an integer. 
The intent of the Data viz. is to highlight the increase in the number of thought leaders in the data viz space. The number of participants in 2018 was less than the other two years. So I decided to omit that year to show contrast. I had also categorized the thought leaders in terms of different identities like- individual/ organization/ event etc. That became another page of the story in which the viewer gets to see who sets the trends. 

The data viz. has been made on Flourish. The link to the same can be found [here.](https://public.flourish.studio/story/88811/)

I enjoyed developing and writing the cover story for the data visualization. I could have gone deeper in the data to make observations about individual leaders. Sharing links to these thought-leaders' work would have made the story solid and end-to-end.

**Comment by akshayrpatil** [comment]
### Initial thoughts:
**# Explorative data visualization/**
1. Firstly I thought of visualizing work experience of professionals in data viz, and peoples pay scale respect to their location and educational background, I started with looking for survey data. It has more than 1320+ entry with 49+ questions.
2. After some failed attempt to explore world data, and discussion with a professor, I narrow down myself to an Indian context.
<img width="1041" alt="Screenshot 2019-11-04 at 3 05 36 AM" src="https://user-images.githubusercontent.com/54841881/68092449-4746ce80-feb1-11e9-8e0f-f297848f196f.png">


**# Data cleaning, data sorting, and deciding variable./**
1. Cleaning takes a longer time as the survey has 49+ questions, I shorted country vise data first and cleaned out Indian country data. After that started deciding (variables)questions from the survey for visualization. My approach here was to use the initial understanding of the survey and to classify the data accordingly, country > city and then > professional role in organizations. 
<img width="929" alt="Screenshot 2019-11-04 at 3 18 36 AM" src="https://user-images.githubusercontent.com/54841881/68092496-ccca7e80-feb1-11e9-8953-eabe089f9118.png">

2. I focused on the following questions from the survey: 
> 1. Have you studied data visualization in school (or other formal environment), or did you learn how to do it on your own?
> 2. Which one of these is the closest to describing your role?
> 3. What is your yearly pay?
> 4. How many years of experience do you have doing professional data visualization?
> 5. What is your educational background
> 6. What city do you live in?

**# Final concept./**
1. Deciding visual legends for visualization.
After brainstorming and initial sketching, I finalized to go with a circle to represent individual entry. 
>reason to choose circle for exploration
>> we can show 3-4 variable (questions responses) by one circle, by changing the color of the circle, size of the circle, adding additional symbol and outline etc.
<img width="688" alt="Screenshot 2019-11-04 at 3 25 10 AM" src="https://user-images.githubusercontent.com/54841881/68092691-b7eeea80-feb3-11e9-99e0-c0488ba35364.png">
2. deciding places of professional proles in the final diagram.
Here the placement of a professional role in organizations is decided by the number of professionals in each category, which helps me to visualize it the better way. 
<img width="357" alt="Screenshot 2019-11-04 at 3 53 24 AM" src="https://user-images.githubusercontent.com/54841881/68092990-02be3180-feb7-11e9-9142-646054a3a91e.png">

>for example, the Analyst category has the most number of people working so I kept it at the outermost circle of the diagram.
<img width="676" alt="Screenshot 2019-11-04 at 4 01 03 AM" src="https://user-images.githubusercontent.com/54841881/68093077-e373d400-feb7-11e9-93ab-d616e8fff23b.png">

**# Final visualization./**
1. The purpose of visualizing Indian professional responses is to show trends and pay-scale of professionals with respect to their working city and experience in data viz.  
2. Here is the small attempt to show where a group of Indian data viz professional live, what are their role in a professional organization, their work experience in data viz, and yearly pay for their professional work. 
3. the high-resolution static image of this visualization can be found [here](https://drive.google.com/drive/u/0/folders/1LFLPfNK0SI-rpR3KcAqWA0Pz9Q0SqNm5).
![1Artboard 1 copy](https://user-images.githubusercontent.com/54841881/68092785-d9040b00-feb4-11e9-9c11-0a1a91d7f4f8.png)

**Comment by rohanjhunja** [comment]
### Timeline of Data Viz Community

**Experience vs Earning vs Freelancing**
Initial explorations of the data in Tableau.
<img width="797" alt="Screenshot 2019-09-20 at 4 18 49 PM" src="https://user-images.githubusercontent.com/54926642/65324264-5efc1900-dbc9-11e9-99fd-4f2de930c822.png">

**Experience vs Motivation**
<img width="797" alt="Screenshot 2019-09-20 at 4 25 14 PM" src="https://user-images.githubusercontent.com/54926642/65324312-7fc46e80-dbc9-11e9-9547-16e40979373e.png">

**People of Data Viz**
This Visualisation displays the composition of the Data Viz community and tells a story of Data Viz as it changes over a 10 year period. Responses from people were grouped by when a member started working in Data Viz.
<img width="1353" alt="Screenshot 2019-10-30 at 10 18 39 PM" src="https://user-images.githubusercontent.com/54926642/67884847-87821600-fb6c-11e9-9a60-2257ea064712.png">


Google charts used to pull data from the source spreadsheets using query language. For this version, only data that could be visualised without any further modification was selected. This included survey questions with single choice, known options.

> =QUERY(A1:B, "select A, count(A) where A is not null and B is not null group by A  pivot B ",1)

The number of respondents from each year varied and people seemed to round off number of years in the field to numbers like 2, 5 and 10. Groups were made to put together almost equal numbers of respondents. Percentages of a 100% column were used to represent data of each group.
<img width="1109" alt="Screenshot 2019-10-29 at 6 31 15 PM" src="https://user-images.githubusercontent.com/54926642/67807487-e38c6200-faba-11e9-85f4-d65f11ebb229.png">

Initial issues include irregular ordering of data in columns and the lack of annotations.
<img width="1109" alt="Screenshot 2019-10-29 at 6 31 46 PM" src="https://user-images.githubusercontent.com/54926642/67807498-e9824300-faba-11e9-9dfd-f57a0b32c32c.png">

FIXED: Ordering of data in chart with largest group lowest, text accompanying viz. _Issue of missing vertical axes yet to be fixed._

Link to the website hosted [here](https://rohanjhunja.github.io/dvschallenge_rj/)
Link to the open files hosted [here](https://github.com/rohanjhunja/dvschallenge_rj/blob/master/index.html)

**Comment by prachitank** [comment]
### Skipped! 

There were 1361*50 data points from the questionnaire. I decided to find the trends in the questions that were left skipped. This seemed like an interesting approach to take, and some initial iterations on Google Sheets itself showed that the number of skipped questions increased as the questionnaire progressed. However there were three types of questions with different trends.
1) Questions requiring check box or radio input 
2) Questions requiring numeric input
3) Questions requiring text input
The trends in each were different and the decision was made to separate them out. 

These trends were interesting by themselves, but they did not complete the visualisation. So two more aspects were added to the visualisation to create a build up to the final. The first one was a representation of all the data followed by the extremes of what the extremes of the data were. 

The final submission can be found [here](https://docs.google.com/spreadsheets/d/1q543dC4T4tdmlpQ-y0SY-J604xYUqivt7JSA8jas1As/edit#gid=245318592).

**Comment by SONIBHAWNA** [comment]
**Iteration 1**
![Tree Map 1](https://user-images.githubusercontent.com/42314455/65326977-59560180-dbd0-11e9-9e36-ce28b30cbab8.png)


**Iteration 2**
![Radial](https://user-images.githubusercontent.com/42314455/65327026-6ffc5880-dbd0-11e9-858d-bcd1ebcd2551.png)

**Iteration 3**
![FINAL ](https://user-images.githubusercontent.com/42314455/65327066-90c4ae00-dbd0-11e9-898f-c9d4490d190d.png)

https://public.flourish.studio/visualisation/690263/

**Comment by dhirajdethe** [comment]
### **How Data Visualization is created and how it is consumed?**

The data survey has covered a whole range of information regarding the data visualization domain. Few of the responses give insights about the data visualization creation process and few give insights about its consumption. In this data visualization, I have tried to tell a story about how data visualization is created and how it is consumed, in the form of a series of visualizations.

I sorted the data from Data survey 2019 and categorized them in categories of Creators and Users. From this data in both the categories, I put them together in the form of questions that an audience might want to ask. Then I created a visualization as an answer to each question.
![1](https://user-images.githubusercontent.com/42227892/67790925-9dc0a100-fa9c-11e9-8541-1f4f6244425e.jpg)
![3](https://user-images.githubusercontent.com/42227892/67876006-3fa7c280-fb5d-11e9-91f6-885b74f7d3a9.jpg)

I sketched out the idea on paper first and then made all the visualizations using the Flourish tool. Using the Html webpage, these questions and visualizations are put together in the form of a series of questions.

![4](https://user-images.githubusercontent.com/42227892/67876068-5221fc00-fb5d-11e9-8490-5db104fb018b.jpg)

![2](https://user-images.githubusercontent.com/42227892/67876084-58b07380-fb5d-11e9-89d7-e4e546f00006.jpg)

Link for the final data visualization is here(https://dhirajdethe.github.io/dvs-challenge/)

**Comment by GauriTillu** [comment]
### **The Story of Data Visualization Education**
For DVS Challenge 2019, I looked at the data of the methods by which data visualizers learned data visualization and the number of years of experience. I have also correlated the gender and the method of learning.

Process used in creating the following visualizations
- Exploring and searching for patterns using basic tools like Google sheet filters.
- Cleaning up the data and selecting the required question set.
- Grouping the experiences into brackets like 0 to 5 years, 6 to 10 years, etc.
- Trying different kinds of visualizations to find the best suited out of the 2-3 narrowed down visualizations. eg. Line graphs in Google sheets, circular visualization using Circos, Sankey using Flourish
- Finalized on Sankey Diagram using Flourish

A few explorations for the visualizations:

Trend line in Google sheets
![Trends in Formal Education in Data Visualization (1)](https://user-images.githubusercontent.com/46102679/65851924-28b15d00-e372-11e9-8f86-74cc02952338.png)

Circular Visualization using Circos
![circos-table-vuylsze-large](https://user-images.githubusercontent.com/46102679/65851849-f273dd80-e371-11e9-8b4b-a9da7f0771c6.png)

Final visualization:
![Screenshot (643)](https://user-images.githubusercontent.com/46102679/65851948-3f57b400-e372-11e9-9b7f-41e8c712336b.png)

**You can find the visualization [here](https://public.flourish.studio/story/88973/)**

**Comment by shraddhadhodi** [comment]
**Initial Idea:**
After looking at the data I first thought of looking into three areas namely:

- Most typically, how often does your audience use your data visualization?
- Who do you make data visualizations for? Select all that apply
- What does your audience use your data visualization for? Select all that apply.
The initial idea was to look for a relationship between what kind of data is produced for what purpose and the frequency at which the data is consumed. 

Although the idea was appealing to work upon, I faced lot of issues while cleaning the data as two of the areas had a multiselection type answer. After trying hard to refine the data I finally decided to work on some other Idea.

**Final Idea:**
To make the task of refining data simple and also to come up with a good presentable visualization I decided to take up an area that is less complicated but meaningful.
Therefore I decided to work with the following questions from the survey:
- Have you studied data visualization in school (or other formal environments) or did you learn how to do it on your own?
- Are you a freelancer/consultant?
- Which one of these is the closest to describing your role?

With these areas, the idea is to bring out the relationship between how people acquired the skill of data visualization to perform what kind of role. Also, the relation could be found when looked into how many of these people are working as a freelancer/consultant or are working full-time with some organizations.
For eg: There are 414 analysts, out of which 81 are freelancers/consultants, 8 are occasional analysts and remaining work as a full-time analyst.

The data was cleared using Ms excel and the visualization has been created using flourish tool which is [here]( https://public.flourish.studio/visualisation/695629/)

**Comment by avyayrkashyap** [comment]
# People in Data Viz
_A career counselling kinda thing, but backed with data..._

As I went through the data for the DVS challenge, I realised there are many fields and professions that make use of data visualisation as a tool. Also, it appeared there were many people doing the same thing. So I initially began this with the idea of figuring how unique a person can be. But this was throwing myself down a rabbit hole, given my limited knowledge in querying and manipulating data in realtime. Thus, I decided to pursue a different question. 

As a novice in this field, I was interested in knowing what future possibilities lay in my path as I studied data viz. This exploration came about as a result of that curiosity, to understand the metrics and judge whether I would want to pursue data visualisation in the future with greater vigour.

I also realised that this is something others might also be interested in knowing. Thus, I began looking at the questions that would help inform me and provide the data to back my decision. 

I primarily considered questions that pertained to things I was doing, such as educational background, process of learning data viz, etc. and things that informed me of the future possibilities, as with the job prospects, pay scale, etc.

As I went through this, a few other factors such as gender and experience also began to seem both relevant and interesting. I chose to keep the professions as a base differentiator, as this essentially would help inform my decision. The data was then cleaned to have over 1000 responses with all questions answered. Ambiguity in answers was removed through this, such as grouping genders from the over eight options to four categories.

In order to show this, I decided to create a declarative data story through Flourish using bar charts and bubble charts. I have chosen a total of 10 questions to help answer my questions. Using Flourish allows me to tell my story, while also letting the user explore other visualisations. The order in which I bring about the questions is related to the answers I was most interested in knowing.

The story can be found [here](https://avyayrkashyap.github.io/rolesindataviz.html).

**Comment by AshmiK** [comment]
Initially the idea was to look at the number of years of experience and the background these people come from and see if those two could be related.
 When going through the responses of various questions, I came across a lot of similar answers, some very unique responses and **_typos_**.
I specifically analysed the spelling mistakes in the names of the thought leaders mentioned by the people. Palladio was used to clean up the data to find the most mentioned thought leaders and the spelling mistakes made by men and women separately (turns out men made more mistakes as compared to women).

![IMG_0480](https://user-images.githubusercontent.com/42314407/67912750-eb2e3280-fbb0-11e9-8305-39599d3c0154.JPG)
Initial idea was to illustrate the most influencing thought leaders along with a sankey diagram of how their names were spelled/misspelled in a fun sort of way but was not carried forward.

Misspelling a name can lead to a lot of confusion (name being an identity of a person and his work). To better depict that a poster was created where images of the thought leaders was treated according to the percentage of misspelled responses. The grain size for the image increased with the increase in the number of mistakes resulting in a more blurry image. All the responses were taken into account irrespective of the gender for this. 
![IMG_0481](https://user-images.githubusercontent.com/42314407/67913170-2715c780-fbb2-11e9-86ac-5338a8e5a0f7.JPG)

Another way to look at this would be thought leader in the data viz world with the hardest names.
However only the top nine thought leaders have been taken into account as after these, a lot of people were mentioned equal number of times.

**Comment by prachitank** [comment]
***SKIPPED

What interested me in the data given by the [DVS 2019 challenge](https://www.datavisualizationsociety.com/2019-survey-challenge) were the questions that respondents had decided to skip. 

The possibilities were to look at the kind of questions respondents skipped most and the associated trends. Another approach that was iterated was to analyse at the answers to try and determine if there is a significant variation between (which I could try and revisit with the new viewpoint and tools that the ongoing statistics course has equipped me with). 

Along with the story that I wanted to tell, I had to decide on the tool that I will be using to tell that story. I started experimenting with Tableau, however, my level of expertise in the same prevented me from using it for exploring the data. This led me to do the same in Google Sheets with the use of conditional formatting and formulae. The Sheets experiment resulted in interesting visuals which I decided to capitalise on. The aim was to make a Google Sheet look like an illustrator document.

I experimented to find out the interesting trends, the types of questions, the outliers and the sections of questions that skewed the data. With this, I cleaned up the data to get to trends over duration (over the entire course of filling the form), analysed the questions which had significantly high or low skip rates separately. 

The final submission can be found [here](https://docs.google.com/spreadsheets/d/1s5GX38KZv998cqN8p0HwWOff6SDWVI44ihH1qWGv4bc/edit#gid=724628969). 
 
Thank You!

**Comment by SaiAnjan** [comment]
# Hours spent in a week by the DVS survey respondents

The final assignment of the course started with discovering the amount of work happening in the Data Viz community. This was the first time I knew that the community of Data Viz is growing after looking at the survey and the responses to it. The survey was among the DV community to understand the differences in practice, tools and audiences of anyone making data visualisation. Following is the ink to the original survey: [Original survey form](https://docs.google.com/forms/d/e/1FAIpQLSe-CMHrt1gYOxO9Tdk6cjyLIpJnAJMDjS94OBDHi6YU2g3sBA/viewform)

Survey for 2019 has responses to 50+ questions and was taken by over 1,350 people. It covers professional data visualization details like salary and hourly compensation, tool use, location, demographic data, audiences, organizational structure and more. 


The assignment was to look at the responses data and guess what, Visualise it! I downloaded the responses data sheet from [here](https://github.com/data-visualization-society/data_visualization_survey). I created another sheet in the file which enlists all the question from the 3 years and interestingly there were additions. I started identifying the questions which were common among the 3 years and I started highlighting them:

<img width="1013" alt="Screenshot 2019-10-31 at 10 47 59 PM" src="https://user-images.githubusercontent.com/29821443/67970120-7e5a7d00-fc30-11e9-876b-a7e552270b26.png">

I noticed that the question about the time spent by the respondents on Data engineering, Data science, Design & Data prep work. Since there were respondents with different professions I wanted to visualise the hours spent in a week by each respondent for the above mentioned categories.


A link to the final visualisation is [here](https://public.flourish.studio/story/111980/)

**Comment by kaishwary08** [comment]
### DVS Survey Challenge

**Starting out**
Dividing and chunking the 50 questions.
![IMG_20190915_203228](https://user-images.githubusercontent.com/54464092/67975185-a7334000-fc39-11e9-9c24-11c725e110ea.jpg)
![IMG_20190915_203235](https://user-images.githubusercontent.com/54464092/67975196-ab5f5d80-fc39-11e9-9719-d30b3aaf8e5f.jpg)

The struggle to work towards finding the right combination of data sets in order to have an interesting story itself was hard to find.

**Comment by seemskk** [comment]
### **Use of Data viz tools among respondents**

From DVS survey, I picked up the part of respondents and their use of data visualisation tools. The first task was to clean up the survey results. This exercise itself was tedious, but good learning in itself. Though my intention was to plot each of the user with the tools used, later I simplified my ambitions to much more achievable levels.

![excel](https://user-images.githubusercontent.com/54902924/68000471-42520700-fc86-11e9-9a23-d90531fe7da8.jpg)

By using Rawgraph's sunburst diagram, plotted the software vs their number of users. This particular diagram visually shows the proportion of users of each software.

![attempt 1](https://user-images.githubusercontent.com/54902924/67969579-9382dc00-fc2f-11e9-94b8-8f5ba19d002b.png)

**Use of data viz tools in Journalism**

From the above data, I just attempted looking at the specific field of journalism and use of tools. Out of the total 1360 respondents, 71 mentioned journalism as their sector of job. Used an alluvial diagram in Rawgraphs to see the results. 

![journalism numbers](https://user-images.githubusercontent.com/54902924/67976551-5244f900-fc3c-11e9-9106-5eba6f1fb2eb.png)

PS: Thanks to Malay for helping me with excel count

**Comment by harsuyash** [comment]
#### The Data set seamed large and mostly qualitative. I decided to color code the data for the categorical attributes and then compare them against each other and find some correlations. 

![Screenshot (322)](https://user-images.githubusercontent.com/54461182/68967941-5c9fef00-0807-11ea-8d70-dd226208b9a2.png)

![Screenshot (335)](https://user-images.githubusercontent.com/54461182/68968051-a5f03e80-0807-11ea-95d9-a75d4c6cb8b3.png)

#### I gathered some selected attributes and sorted them to see some color patterns emerging (indicating patterns in the data)

![Screenshot (336)](https://user-images.githubusercontent.com/54461182/68968125-d2a45600-0807-11ea-823b-8753fb3b04d2.png)

#### After making the cells extremely small and zooming out all the way I could see the bigger picture and the data already getting visualized.

# 1. The varied roles of Data Visualizers and income

![Role and income DVS-01](https://user-images.githubusercontent.com/54461182/68968419-80176980-0808-11ea-9503-7777d7cdd271.png)

These were some quick data exploration that turned into visual confirmation.
#### We can observe the concentrated white bars over leadership roles and engineers indicating high income and some darker bars over students, scientists, designers and academicians

# 2. Years of experience and income
 
![Exp-01](https://user-images.githubusercontent.com/54461182/68969003-ed77ca00-0809-11ea-8479-bebf09586c08.png)

#### There are lighter bars at the end (20-30 years experience) but a lot of light red areas are seen #### even with <5 years experience.
**Note:** The scale is skewed because the length of interval is determined by no. of responses for that interval of data (as this is taken directly from excel)

# 3. Which role has people hired as full time Data visualizers and which one has it as a part of job

![Part DVS-01](https://user-images.githubusercontent.com/54461182/68969280-96262980-080a-11ea-8029-84d8127c1208.png)

#### The blue bars indicate that they are hired to do Data Visualization specifically I did not expect these results but it seems the blue bars are mostly hovering over designer and also many over developers

#### After these explorations that indeed revealed some visual patterns, I decided to narrow down on these roles and create a visualization around:
## Who makes data visualization for whom?
### How people with different roles interact as both creators and consumers 
#### What I could visualize in my head was similar to an Alluvial chart

#### The required a lot of cleaning
![Screenshot (337)](https://user-images.githubusercontent.com/54461182/68969606-6297cf00-080b-11ea-8b77-77f1b157d6fa.png)

#### I filtered out some major responses and grouped the rare ones like librarian, lawyer, Government officials, investments etc. into others.
![Screenshot (338)](https://user-images.githubusercontent.com/54461182/68969727-ae4a7880-080b-11ea-96c4-c5120ceb3e71.png)
#### And made the data suitable for an Alluvial chart template.
#### The Data revealed how most of the data viz is done for executives and project managers and the major contribution towards general public consumption is by analysts and designers. 
![Screenshot (344)](https://user-images.githubusercontent.com/54461182/68970115-9a534680-080c-11ea-9a6b-d0bc1f1988e7.png)
![Screenshot (343)](https://user-images.githubusercontent.com/54461182/68970126-9f17fa80-080c-11ea-84e8-903dda68682a.png)

### The final VIZ can be seen [here](https://public.flourish.studio/visualisation/934752/)

**Comment by harshitsatija** [comment]
### **A guide to 'Data Visualization as a job'**

When I first saw the data, Original survey form, I was overwhelmed by the sheer number of answers. After seeing the types of questions, I started forming some affinities and tried to find something interesting in Tableau. The initial ideas were to look at correlations between questions like :

**"Are you able to choose your own tools or are the choices made for you?" and "Hours a week focused on creating/implementing/productizing data visualizations?"** 

![1](https://user-images.githubusercontent.com/54463355/68973978-9c6dd300-0815-11ea-8e24-0d7c174d6583.JPG)

**or "What focus is data visualization in your work?" and "What country do you live in?".**  

![2](https://user-images.githubusercontent.com/54463355/68974005-abed1c00-0815-11ea-8eae-17d684ea4b12.JPG)

After going through the data, some more I saw an opportunity to explore as well as answer my question of how Data Visualization can be as a job. 
After realizing what question to answer, I made some visualizations in Tableau.

![3](https://user-images.githubusercontent.com/54463355/68974043-c45d3680-0815-11ea-87f2-d8f3be87ffb6.JPG)

![4](https://user-images.githubusercontent.com/54463355/68974051-ca531780-0815-11ea-9cc7-3f5b7669324d.JPG)

Once I had set the central theme, the questions I had to answer through the visualizations became clear. I cleaned the dataset for the set of visualizations, which is linked [here.](https://drive.google.com/file/d/1Kz6lgXbaF2bV8DwEH-U1sWBLa0q1qRSG/view?usp=sharing)`

The final story was made using flourish which is posted [here.](https://app.flourish.studio/story/124232/)

**Comment by aishaanam** [comment]
I initially tried to segregate each tool to find what tool is used most. But Data cleaning was too tedious so, I created visualization which sees what number of men & women are into Data visualization from different countries. Here is the link.
[<div class="flourish-embed" data-src="visualisation/1026935"></div><script src="https://public.flourish.studio/resources/embed.js"></script>](url)
![Gender_Data Visualizers   Countries](https://user-images.githubusercontent.com/43089695/69946027-cf4fe080-1510-11ea-8160-6065aa2f918a.png)
